#!/usr/bin/env node
'use strict';

/**
 * Strict RFC-001 M2 -> OWL projection.
 *
 * `projectOwl(document)` is a pure projection and returns the generated bytes.
 * The CLI wrapper reads one source file and writes only to the caller-supplied
 * output path (or stdout with `-`); it never derives or rewrites a source-side
 * output path.
 */

const fs = require('node:fs');
const path = require('node:path');
const yaml = require('js-yaml');
const {
  FACT_IDENTITY,
  FACT_VERSION,
  MONEY,
  NS,
  PATTERNS,
  QUANTITY,
  SOURCE_EVIDENCE,
  addRdfList,
  addTriple,
  attributeProjection,
  blankNode,
  literal,
  namedNode,
  rolePredicate,
  serializeTurtle,
  shortDigest,
  sortedEntries,
  sortedValues,
  validateDocument,
  VERSION_OF,
} = require('./lib/typed-projection-common.cjs');
const {
  effectivePatternInjectedAttributeUses,
} = require('./lib/pattern-injected-fields.cjs');

const EXACT_VERSION_REFERENCE =
  'https://axiolune.ai/ontology/meta/core/constraints/ExactVersionReference';
const LOGICAL_REFERENCE =
  'https://axiolune.ai/ontology/meta/core/constraints/LogicalReference';
const REFERENCE_MODE_CONSTRAINTS = new Set([
  EXACT_VERSION_REFERENCE,
  LOGICAL_REFERENCE,
]);

const CHARACTERISTIC_TYPES = Object.freeze({
  functional: `${NS.OWL}FunctionalProperty`,
  inverseFunctional: `${NS.OWL}InverseFunctionalProperty`,
  transitive: `${NS.OWL}TransitiveProperty`,
  symmetric: `${NS.OWL}SymmetricProperty`,
  asymmetric: `${NS.OWL}AsymmetricProperty`,
  reflexive: `${NS.OWL}ReflexiveProperty`,
  irreflexive: `${NS.OWL}IrreflexiveProperty`,
});

const META_ONTOLOGY = 'https://axiolune.ai/ontology/meta';

const ALIGNMENT_PREDICATES = Object.freeze({
  'rdfs:subClassOf': `${NS.RDFS}subClassOf`,
  'rdfs:subPropertyOf': `${NS.RDFS}subPropertyOf`,
  'owl:equivalentClass': `${NS.OWL}equivalentClass`,
  'owl:equivalentProperty': `${NS.OWL}equivalentProperty`,
  'skos:closeMatch': `${NS.SKOS}closeMatch`,
  'skos:exactMatch': `${NS.SKOS}exactMatch`,
  'skos:broadMatch': `${NS.SKOS}broadMatch`,
  'skos:narrowMatch': `${NS.SKOS}narrowMatch`,
  'skos:relatedMatch': `${NS.SKOS}relatedMatch`,
});

const SKOS_DECLARATIONS = Object.freeze([
  [`${NS.SKOS}Concept`, `${NS.OWL}Class`],
  [`${NS.SKOS}ConceptScheme`, `${NS.OWL}Class`],
  [`${NS.SKOS}prefLabel`, `${NS.OWL}AnnotationProperty`],
  [`${NS.SKOS}notation`, `${NS.OWL}DatatypeProperty`],
  [`${NS.SKOS}inScheme`, `${NS.OWL}ObjectProperty`],
  [`${NS.SKOS}closeMatch`, `${NS.OWL}ObjectProperty`],
  [`${NS.SKOS}exactMatch`, `${NS.OWL}ObjectProperty`],
  [`${NS.SKOS}broadMatch`, `${NS.OWL}ObjectProperty`],
  [`${NS.SKOS}narrowMatch`, `${NS.OWL}ObjectProperty`],
  [`${NS.SKOS}relatedMatch`, `${NS.OWL}ObjectProperty`],
]);

// OWL 2's normative datatype map does not include xsd:date or xsd:duration.
// The M3 authoring model deliberately retains those RDF datatypes for
// calendar-date and duration values, so strict OWL parsers need explicit
// datatype declarations before those IRIs can occur in property ranges.
const EXPLICIT_XSD_DATATYPE_DECLARATIONS = Object.freeze([
  `${NS.XSD}date`,
  `${NS.XSD}duration`,
]);

function propertyTypeForProjection(projection) {
  if (projection.kind === 'object') return `${NS.OWL}ObjectProperty`;
  if (projection.kind === 'annotation') return `${NS.OWL}AnnotationProperty`;
  return `${NS.OWL}DatatypeProperty`;
}

function alignmentTargetDeclaration(model, containerName, element, alignment) {
  if (alignment.relation === 'rdfs:subClassOf'
      || alignment.relation === 'owl:equivalentClass') {
    return `${NS.OWL}Class`;
  }
  if (alignment.relation === 'rdfs:subPropertyOf'
      || alignment.relation === 'owl:equivalentProperty') {
    if (containerName === 'relationTypes') return `${NS.OWL}ObjectProperty`;
    if (containerName === 'attributeTypes') {
      const declaration = propertyTypeForProjection(attributeProjection(model, element));
      if (alignment.relation === 'owl:equivalentProperty'
          && declaration === `${NS.OWL}AnnotationProperty`) {
        throw new Error(
          `${element.iri}.alignments: owl:equivalentProperty cannot align an OWL annotation property`,
        );
      }
      return declaration;
    }
  }
  if (alignment.relation.startsWith('skos:')) return `${NS.OWL}NamedIndividual`;
  throw new Error(
    `${element.iri}.alignments: cannot derive an OWL entity declaration for ${alignment.relation}`,
  );
}

function hasTriple(quads, subject, predicate, object) {
  return quads.some((entry) => (
    entry.subject.termType === 'NamedNode'
    && entry.subject.value === subject
    && entry.predicate.termType === 'NamedNode'
    && entry.predicate.value === predicate
    && entry.object.termType === 'NamedNode'
    && entry.object.value === object
  ));
}

function assertStrictOwlStructure(quads, model) {
  const ontologyIri = model.module.moduleIri;
  if (!hasTriple(quads, ontologyIri, `${NS.OWL}imports`, META_ONTOLOGY)) {
    throw new Error(`${ontologyIri}: strict OWL projection must import ${META_ONTOLOGY}`);
  }
  for (const [entityIri, declaration] of SKOS_DECLARATIONS) {
    if (!hasTriple(quads, entityIri, `${NS.RDF}type`, declaration)) {
      throw new Error(`${entityIri}: missing strict OWL entity declaration ${declaration}`);
    }
  }
  for (const datatypeIri of EXPLICIT_XSD_DATATYPE_DECLARATIONS) {
    if (!hasTriple(quads, datatypeIri, `${NS.RDF}type`, `${NS.RDFS}Datatype`)) {
      throw new Error(`${datatypeIri}: missing strict OWL datatype declaration`);
    }
  }
  const restrictionSubjects = new Map();
  for (const entry of quads) {
    if (entry.subject.termType !== 'BlankNode') continue;
    const subject = entry.subject.value;
    if (!restrictionSubjects.has(subject)) restrictionSubjects.set(subject, []);
    restrictionSubjects.get(subject).push(entry);
  }
  for (const [subject, entries] of restrictionSubjects) {
    const isRestriction = entries.some((entry) => (
      entry.predicate.value === `${NS.RDF}type`
      && entry.object.termType === 'NamedNode'
      && entry.object.value === `${NS.OWL}Restriction`
    ));
    if (!isRestriction) continue;
    const isClass = entries.some((entry) => (
      entry.predicate.value === `${NS.RDF}type`
      && entry.object.termType === 'NamedNode'
      && entry.object.value === `${NS.OWL}Class`
    ));
    if (!isClass) {
      throw new Error(`_:${subject}: owl:Restriction must also be explicitly typed owl:Class`);
    }
    const cardinalityPredicates = new Set([
      `${NS.OWL}cardinality`,
      `${NS.OWL}minCardinality`,
      `${NS.OWL}maxCardinality`,
      `${NS.OWL}qualifiedCardinality`,
      `${NS.OWL}minQualifiedCardinality`,
      `${NS.OWL}maxQualifiedCardinality`,
    ]);
    const cardinalities = entries.filter((entry) => cardinalityPredicates.has(entry.predicate.value));
    if (cardinalities.length !== 1) {
      throw new Error(
        `_:${subject}: strict restriction must contain exactly one cardinality predicate`,
      );
    }
  }
  for (const containerName of [
    'objectTypes',
    'associationTypes',
    'relationTypes',
    'attributeTypes',
    'identifierTypes',
    'codeLists',
  ]) {
    for (const element of Object.values(model.domain[containerName])) {
      for (const alignment of element.alignments || []) {
        const predicate = ALIGNMENT_PREDICATES[alignment.relation];
        const declaration = alignmentTargetDeclaration(
          model,
          containerName,
          element,
          alignment,
        );
        if (!hasTriple(quads, element.iri, predicate, alignment.targetIri)) {
          throw new Error(
            `${element.iri}.alignments: missing generated ${alignment.relation} assertion`,
          );
        }
        if (!hasTriple(
          quads,
          alignment.targetIri,
          `${NS.RDF}type`,
          declaration,
        )) {
          throw new Error(
            `${alignment.targetIri}: missing alignment-target OWL declaration ${declaration}`,
          );
        }
      }
    }
  }
}

function addStandardVocabularyDeclarations(quads) {
  for (const [entityIri, declaration] of SKOS_DECLARATIONS) {
    addTriple(
      quads,
      namedNode(entityIri),
      namedNode(`${NS.RDF}type`),
      namedNode(declaration),
    );
  }
  for (const datatypeIri of EXPLICIT_XSD_DATATYPE_DECLARATIONS) {
    addTriple(
      quads,
      namedNode(datatypeIri),
      namedNode(`${NS.RDF}type`),
      namedNode(`${NS.RDFS}Datatype`),
    );
  }
}

function addLabelAndDefinition(quads, subject, element) {
  addTriple(quads, subject, namedNode(`${NS.RDFS}label`), literal(element.label));
  addTriple(quads, subject, namedNode(`${NS.RDFS}comment`), literal(element.definition));
}

function addQualifiedRestrictionNode(
  quads,
  ownerClass,
  propertyIri,
  rangeIri,
  predicateIri,
  cardinality,
  seed,
) {
  const restriction = blankNode(`r_${shortDigest(seed)}`);
  addTriple(quads, ownerClass, namedNode(`${NS.RDFS}subClassOf`), restriction);
  addTriple(quads, restriction, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}Class`));
  addTriple(quads, restriction, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}Restriction`));
  addTriple(quads, restriction, namedNode(`${NS.OWL}onProperty`), namedNode(propertyIri));
  addTriple(quads, restriction, namedNode(`${NS.OWL}onClass`), namedNode(rangeIri));
  addTriple(
    quads,
    restriction,
    namedNode(predicateIri),
    literal(String(cardinality), namedNode(`${NS.XSD}nonNegativeInteger`)),
  );
}

function addQualifiedRestriction(
  quads,
  ownerClass,
  propertyIri,
  rangeIri,
  role,
  seed,
) {
  const cardinality = {
    minCount: role.minCount ?? 0,
    maxCount: role.maxCount ?? null,
  };
  if (cardinality.maxCount !== null && cardinality.minCount === cardinality.maxCount) {
    addQualifiedRestrictionNode(
      quads,
      ownerClass,
      propertyIri,
      rangeIri,
      `${NS.OWL}qualifiedCardinality`,
      cardinality.minCount,
      `${seed}\0exact`,
    );
    return;
  }
  addQualifiedRestrictionNode(
    quads,
    ownerClass,
    propertyIri,
    rangeIri,
    `${NS.OWL}minQualifiedCardinality`,
    cardinality.minCount,
    `${seed}\0min`,
  );
  if (cardinality.maxCount !== null) {
    addQualifiedRestrictionNode(
      quads,
      ownerClass,
      propertyIri,
      rangeIri,
      `${NS.OWL}maxQualifiedCardinality`,
      cardinality.maxCount,
      `${seed}\0max`,
    );
  }
}

function addUnqualifiedCardinalityRestriction(quads, ownerClass, propertyIri, role, seed) {
  const minCount = role.minCount ?? 0;
  const maxCount = role.maxCount ?? null;
  const add = (predicateIri, value, suffix) => {
    const restriction = blankNode(`r_${shortDigest(`${seed}\0${suffix}`)}`);
    addTriple(quads, ownerClass, namedNode(`${NS.RDFS}subClassOf`), restriction);
    addTriple(quads, restriction, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}Class`));
    addTriple(quads, restriction, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}Restriction`));
    addTriple(quads, restriction, namedNode(`${NS.OWL}onProperty`), namedNode(propertyIri));
    addTriple(
      quads,
      restriction,
      namedNode(predicateIri),
      literal(String(value), namedNode(`${NS.XSD}nonNegativeInteger`)),
    );
  };
  if (maxCount !== null && minCount === maxCount) {
    add(`${NS.OWL}cardinality`, minCount, 'exact');
    return;
  }
  add(`${NS.OWL}minCardinality`, minCount, 'min');
  if (maxCount !== null) add(`${NS.OWL}maxCardinality`, maxCount, 'max');
}

function addPatternInjectedRestrictions(quads, element) {
  const ownerClass = namedNode(element.iri);
  for (const use of effectivePatternInjectedAttributeUses(element)) {
    if (use.owlCardinality !== true) continue;
    addUnqualifiedCardinalityRestriction(
      quads,
      ownerClass,
      use.attribute,
      use,
      `${element.iri}\0${use.pattern}\0${use.attribute}`,
    );
  }
}

function addAuthoredAttributeRestrictions(quads, model, element) {
  const ownerClass = namedNode(element.iri);
  const uses = [...(element.attributeUses || [])].sort((left, right) => (
    Buffer.compare(Buffer.from(left.attribute, 'utf8'), Buffer.from(right.attribute, 'utf8'))
  ));
  for (const use of uses) {
    const symbol = model.symbols.get(use.attribute);
    const definition = symbol?.kind === 'attributeTypes' ? symbol.element : null;
    if (symbol && !definition) {
      throw new Error(
        `${element.iri}.attributeUses: ${use.attribute} is not an AttributeTypeDefinition`,
      );
    }
    const cardinality = {
      minCount: use.minCount ?? definition?.defaultCardinality?.minCount ?? 0,
      maxCount: use.maxCount ?? definition?.defaultCardinality?.maxCount ?? null,
    };
    const seed = `${element.iri}\0authored-attribute\0${use.attribute}`;

    // Imported attributes deliberately remain modular: the imported ontology
    // owns their property kind and range, while this module owns only the
    // contextual cardinality asserted by its AttributeUse.
    if (!definition) {
      addUnqualifiedCardinalityRestriction(
        quads,
        ownerClass,
        use.attribute,
        cardinality,
        seed,
      );
      continue;
    }

    const projection = attributeProjection(model, definition);
    if (projection.kind === 'annotation') {
      throw new Error(
        `${element.iri}.attributeUses: authored AttributeUse ${use.attribute} cannot target an OWL annotation property`,
      );
    }
    if (projection.kind === 'object') {
      addQualifiedRestriction(
        quads,
        ownerClass,
        use.attribute,
        projection.range,
        cardinality,
        seed,
      );
    } else {
      addUnqualifiedCardinalityRestriction(
        quads,
        ownerClass,
        use.attribute,
        cardinality,
        seed,
      );
    }
  }
}

function logicalIdentityClassIri(typeIri) {
  return `${typeIri}/LogicalIdentity`;
}

function isVersionedType(element) {
  return (element.patternBindings || []).some((binding) => binding.pattern === PATTERNS.temporal);
}

function addIdentityProjectionAxioms(quads, element) {
  if (!isVersionedType(element) || element.abstract === true) return;
  const versionClass = namedNode(element.iri);
  const identityIri = logicalIdentityClassIri(element.iri);
  const identityClass = namedNode(identityIri);
  addTriple(quads, identityClass, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}Class`));
  addTriple(quads, identityClass, namedNode(`${NS.RDFS}subClassOf`), namedNode(FACT_IDENTITY));
  addTriple(quads, identityClass, namedNode(`${NS.OWL}disjointWith`), namedNode(FACT_VERSION));
  addTriple(
    quads,
    identityClass,
    namedNode(`${NS.RDFS}label`),
    literal(`${element.label} logical identity`),
  );
  addTriple(
    quads,
    identityClass,
    namedNode(`${NS.RDFS}comment`),
    literal(`Stable FactIdentity companion for immutable ${element.label} versions.`),
  );
  addQualifiedRestriction(
    quads,
    versionClass,
    VERSION_OF,
    identityIri,
    { minCount: 1, maxCount: 1 },
    `${element.iri}\0versionOf`,
  );
}

function referenceMode(constraints, expectedTarget, pathValue) {
  const matches = (constraints || []).filter(
    (constraint) => REFERENCE_MODE_CONSTRAINTS.has(constraint.constraintRef),
  );
  if (matches.length > 1) {
    throw new Error(`${pathValue}: expected at most one reference-mode constraint`);
  }
  if (matches.length === 0) return null;
  if (matches[0].targetElement !== undefined && matches[0].targetElement !== expectedTarget) {
    throw new Error(`${pathValue}: reference-mode targetElement must equal ${expectedTarget}`);
  }
  return matches[0].constraintRef === EXACT_VERSION_REFERENCE ? 'exact' : 'logical';
}

function participantRoleReferenceMode(model, association, role) {
  const predicateIri = rolePredicate(association.iri, role.id);
  const bindings = model.domain.constraintBindings.filter((binding) => (
    binding.targetElement === predicateIri
      && REFERENCE_MODE_CONSTRAINTS.has(binding.constraintRef)
  ));
  return referenceMode(
    bindings,
    predicateIri,
    `${association.iri}.participantRoles.${role.id}`,
  );
}

function relationUseReferenceMode(use) {
  return referenceMode(
    use.constraints,
    use.relation,
    `${use.subjectType}.relationUses.${use.relation}`,
  );
}

function referenceRange(rangeIri, mode) {
  return mode === 'logical' ? logicalIdentityClassIri(rangeIri) : rangeIri;
}

function addAlignment(quads, model, containerName, element) {
  for (const alignment of element.alignments || []) {
    if (!alignment || typeof alignment !== 'object' || !alignment.targetIri) {
      throw new Error(`${element.iri}.alignments: invalid Alignment`);
    }
    const predicate = ALIGNMENT_PREDICATES[alignment.relation];
    if (!predicate) {
      throw new Error(`${element.iri}.alignments: unsupported relation ${alignment.relation}`);
    }
    const targetDeclaration = alignmentTargetDeclaration(
      model,
      containerName,
      element,
      alignment,
    );
    addTriple(
      quads,
      namedNode(alignment.targetIri),
      namedNode(`${NS.RDF}type`),
      namedNode(targetDeclaration),
    );
    addTriple(quads, namedNode(element.iri), namedNode(predicate), namedNode(alignment.targetIri));
  }
}

function addPatternAxioms(quads, element) {
  const type = namedNode(element.iri);
  for (const binding of element.patternBindings || []) {
    addTriple(quads, type, namedNode(`${NS.RDFS}subClassOf`), namedNode(binding.pattern));
    if (binding.pattern === PATTERNS.temporal) {
      addTriple(quads, type, namedNode(`${NS.RDFS}subClassOf`), namedNode(FACT_VERSION));
    }
  }
  addPatternInjectedRestrictions(quads, element);
}

function addCodeList(quads, codeList) {
  const listClass = namedNode(codeList.iri);
  const scheme = namedNode(`${codeList.iri}/scheme`);
  addTriple(quads, listClass, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}Class`));
  addLabelAndDefinition(quads, listClass, codeList);
  addTriple(quads, scheme, namedNode(`${NS.RDF}type`), namedNode(`${NS.SKOS}ConceptScheme`));
  addTriple(quads, scheme, namedNode(`${NS.SKOS}prefLabel`), literal(codeList.label));
  addTriple(quads, scheme, namedNode(SOURCE_EVIDENCE), namedNode(codeList.sourceEvidenceRef));

  const members = sortedValues(codeList.values);
  const memberTerms = members.map((member) => namedNode(member.iri));
  const listHead = addRdfList(quads, memberTerms, `owl-one-of\0${codeList.iri}`);
  addTriple(quads, listClass, namedNode(`${NS.OWL}oneOf`), listHead);

  for (const member of members) {
    const memberNode = namedNode(member.iri);
    addTriple(quads, memberNode, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}NamedIndividual`));
    addTriple(quads, memberNode, namedNode(`${NS.RDF}type`), listClass);
    addTriple(quads, memberNode, namedNode(`${NS.RDF}type`), namedNode(`${NS.SKOS}Concept`));
    addTriple(quads, memberNode, namedNode(`${NS.SKOS}inScheme`), scheme);
    addTriple(quads, memberNode, namedNode(`${NS.SKOS}prefLabel`), literal(member.label));
    addTriple(quads, memberNode, namedNode(`${NS.SKOS}notation`), literal(member.notation));
    addTriple(quads, memberNode, namedNode(`${NS.RDFS}comment`), literal(member.definition));
    addTriple(
      quads,
      memberNode,
      namedNode(SOURCE_EVIDENCE),
      namedNode(member.sourceEvidenceRef || codeList.sourceEvidenceRef),
    );
    if (member.deprecated === true) {
      addTriple(
        quads,
        memberNode,
        namedNode(`${NS.OWL}deprecated`),
        literal('true', namedNode(`${NS.XSD}boolean`)),
      );
    }
    if (member.replacedBy) {
      addTriple(
        quads,
        memberNode,
        namedNode(`${NS.DCTERMS}isReplacedBy`),
        namedNode(member.replacedBy),
      );
    }
  }
}

function addAttribute(quads, model, attribute) {
  const projection = attributeProjection(model, attribute);
  const property = namedNode(attribute.iri);
  const propertyType = propertyTypeForProjection(projection);
  addTriple(quads, property, namedNode(`${NS.RDF}type`), namedNode(propertyType));
  addLabelAndDefinition(quads, property, attribute);
  if (projection.range) {
    addTriple(quads, property, namedNode(`${NS.RDFS}range`), namedNode(projection.range));
  }
}

async function projectOwl(document) {
  const model = validateDocument(document);
  const quads = [];
  const ontology = namedNode(model.module.moduleIri);

  addTriple(quads, ontology, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}Ontology`));
  addTriple(
    quads,
    ontology,
    namedNode(`${NS.OWL}versionIRI`),
    namedNode(`${model.module.moduleIri}/${model.module.version}`),
  );
  addTriple(quads, ontology, namedNode(`${NS.RDFS}label`), literal(model.module.label));
  addTriple(quads, ontology, namedNode(`${NS.RDFS}comment`), literal(model.module.definition));
  addTriple(
    quads,
    ontology,
    namedNode(`${NS.OWL}imports`),
    namedNode(META_ONTOLOGY),
  );
  for (const moduleImport of model.module.imports) {
    if (!moduleImport || typeof moduleImport.moduleIri !== 'string') {
      throw new Error('module.imports: every import must contain moduleIri');
    }
    addTriple(
      quads,
      ontology,
      namedNode(`${NS.OWL}imports`),
      namedNode(moduleImport.moduleIri),
    );
  }
  addStandardVocabularyDeclarations(quads);

  for (const [, objectType] of sortedEntries(model.domain.objectTypes)) {
    const type = namedNode(objectType.iri);
    addTriple(quads, type, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}Class`));
    addLabelAndDefinition(quads, type, objectType);
    for (const superType of objectType.superTypes || []) {
      addTriple(quads, type, namedNode(`${NS.RDFS}subClassOf`), namedNode(superType));
    }
    addPatternAxioms(quads, objectType);
    addIdentityProjectionAxioms(quads, objectType);
    addAuthoredAttributeRestrictions(quads, model, objectType);
    addAlignment(quads, model, 'objectTypes', objectType);
  }

  for (const [, association] of sortedEntries(model.domain.associationTypes)) {
    const associationClass = namedNode(association.iri);
    addTriple(quads, associationClass, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}Class`));
    addLabelAndDefinition(quads, associationClass, association);
    addPatternAxioms(quads, association);
    addIdentityProjectionAxioms(quads, association);
    addAuthoredAttributeRestrictions(quads, model, association);
    association.participantRoles
      .slice()
      .sort((a, b) => Buffer.compare(Buffer.from(a.id, 'utf8'), Buffer.from(b.id, 'utf8')))
      .forEach((role) => {
        const predicateIri = rolePredicate(association.iri, role.id);
        const mode = participantRoleReferenceMode(model, association, role);
        const rangeIri = referenceRange(role.range, mode);
        const predicate = namedNode(predicateIri);
        addTriple(quads, predicate, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}ObjectProperty`));
        addTriple(quads, predicate, namedNode(`${NS.RDFS}domain`), associationClass);
        addTriple(quads, predicate, namedNode(`${NS.RDFS}range`), namedNode(rangeIri));
        if (role.label) addTriple(quads, predicate, namedNode(`${NS.RDFS}label`), literal(role.label));
        if (role.definition) {
          addTriple(quads, predicate, namedNode(`${NS.RDFS}comment`), literal(role.definition));
        }
        addQualifiedRestriction(
          quads,
          associationClass,
          predicateIri,
          rangeIri,
          role,
          `${association.iri}\0${role.id}\0${mode || 'untyped'}`,
        );
      });
    addAlignment(quads, model, 'associationTypes', association);
  }

  for (const [, relation] of sortedEntries(model.domain.relationTypes)) {
    const uses = model.domain.relationUses.filter((use) => use.relation === relation.iri);
    const modes = new Set(uses.map(relationUseReferenceMode).filter(Boolean));
    if (modes.size > 1) {
      throw new Error(`${relation.iri}: one OWL property cannot carry mixed reference modes`);
    }
    const mode = modes.size === 1 ? [...modes][0] : null;
    const rangeIri = referenceRange(relation.range, mode);
    const property = namedNode(relation.iri);
    addTriple(quads, property, namedNode(`${NS.RDF}type`), namedNode(`${NS.OWL}ObjectProperty`));
    addLabelAndDefinition(quads, property, relation);
    addTriple(quads, property, namedNode(`${NS.RDFS}domain`), namedNode(relation.domain));
    addTriple(quads, property, namedNode(`${NS.RDFS}range`), namedNode(rangeIri));
    if (relation.inverseOf) {
      addTriple(quads, property, namedNode(`${NS.OWL}inverseOf`), namedNode(relation.inverseOf));
    }
    for (const characteristic of relation.characteristics || []) {
      if (!CHARACTERISTIC_TYPES[characteristic]) {
        throw new Error(`${relation.iri}.characteristics: unsupported ${characteristic}`);
      }
      addTriple(
        quads,
        property,
        namedNode(`${NS.RDF}type`),
        namedNode(CHARACTERISTIC_TYPES[characteristic]),
      );
    }
    addAlignment(quads, model, 'relationTypes', relation);
  }

  model.domain.relationUses
    .slice()
    .sort((left, right) => Buffer.compare(
      Buffer.from(`${left.relation}\0${left.subjectType}\0${left.objectType}`, 'utf8'),
      Buffer.from(`${right.relation}\0${right.subjectType}\0${right.objectType}`, 'utf8'),
    ))
    .forEach((use) => {
      const mode = relationUseReferenceMode(use);
      addQualifiedRestriction(
        quads,
        namedNode(use.subjectType),
        use.relation,
        referenceRange(use.objectType, mode),
        {
          minCount: use.outboundCardinality?.minCount ?? 0,
          maxCount: use.outboundCardinality?.maxCount ?? null,
        },
        `${use.subjectType}\0${use.relation}\0${use.objectType}\0${mode || 'untyped'}`,
      );
    });

  for (const [, attribute] of sortedEntries(model.domain.attributeTypes)) {
    addAttribute(quads, model, attribute);
    addAlignment(quads, model, 'attributeTypes', attribute);
  }

  for (const [, identifier] of sortedEntries(model.domain.identifierTypes)) {
    const datatype = namedNode(identifier.iri);
    addTriple(quads, datatype, namedNode(`${NS.RDF}type`), namedNode(`${NS.RDFS}Datatype`));
    addLabelAndDefinition(quads, datatype, identifier);
    addAlignment(quads, model, 'identifierTypes', identifier);
  }

  for (const [, codeList] of sortedEntries(model.domain.codeLists)) {
    addCodeList(quads, codeList);
    addAlignment(quads, model, 'codeLists', codeList);
  }

  assertStrictOwlStructure(quads, model);

  return serializeTurtle(quads, {
    dcterms: NS.DCTERMS,
    owl: NS.OWL,
    rdf: NS.RDF,
    rdfs: NS.RDFS,
    skos: NS.SKOS,
    xsd: NS.XSD,
    [model.module.preferredPrefix]: model.module.baseIri,
  });
}

async function runCli(argv = process.argv.slice(2)) {
  if (argv.length !== 2) {
    throw new Error('Usage: node generate-m2-owl.cjs <module.yaml> <output.ttl|->');
  }
  const [inputFile, outputFile] = argv;
  const resolvedInput = path.resolve(inputFile);
  if (!fs.existsSync(resolvedInput)) throw new Error(`${inputFile}: not found`);
  const resolvedOutput = outputFile === '-' ? null : path.resolve(outputFile);
  const pathKey = (value) => (
    process.platform === 'win32' ? value.toLowerCase() : value
  );
  const aliasesInput = resolvedOutput !== null && (
    pathKey(resolvedOutput) === pathKey(resolvedInput)
    || (fs.existsSync(resolvedOutput)
      && fs.statSync(resolvedOutput).dev === fs.statSync(resolvedInput).dev
      && fs.statSync(resolvedOutput).ino === fs.statSync(resolvedInput).ino)
  );
  if (aliasesInput) {
    throw new Error('output path must not overwrite the source module');
  }
  const document = yaml.load(fs.readFileSync(resolvedInput, 'utf8'));
  const bytes = await projectOwl(document);
  if (outputFile === '-') {
    process.stdout.write(bytes);
  } else {
    fs.mkdirSync(path.dirname(resolvedOutput), { recursive: true });
    fs.writeFileSync(resolvedOutput, bytes);
  }
  return bytes;
}

if (require.main === module) {
  runCli().catch((error) => {
    console.error(`${error.code ? `${error.code}: ` : ''}${error.message}`);
    process.exitCode = 1;
  });
}

module.exports = {
  ALIGNMENT_PREDICATES,
  EXACT_VERSION_REFERENCE,
  EXPLICIT_XSD_DATATYPE_DECLARATIONS,
  META_ONTOLOGY,
  LOGICAL_REFERENCE,
  SKOS_DECLARATIONS,
  alignmentTargetDeclaration,
  logicalIdentityClassIri,
  assertStrictOwlStructure,
  projectOwl,
  runCli,
};
