module:
  moduleIri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/
  baseIri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/
  preferredPrefix: fibo-loan-loaloa
  version: local
  label: Loan Applications Ontology
  definition: This ontology defines concepts for the loan application process, along with kinds of loan application and the
    parties thereto. Another major thread of this ontology is credit risk assessment at the highest level, which includes
    security agreements, pre-approvals, and credit reports.
  imports:
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FBC/DebtAndEquities/CreditRatings/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FBC/DebtAndEquities/Debt/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/ClientsAndAccounts/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/CurrencyAmount/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FND/Agreements/Contracts/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Assessments/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Lifecycles/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Reporting/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FND/DatesAndTimes/FinancialDates/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FND/DatesAndTimes/Occurrences/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FND/OwnershipAndControl/Ownership/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/Analytics/
    version: external
  - moduleIri: https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/AnnotationVocabulary/
    version: external
  - moduleIri: https://www.omg.org/spec/Commons/AnnotationVocabulary/
    version: external
  - moduleIri: https://www.omg.org/spec/Commons/Classifiers/
    version: external
  - moduleIri: https://www.omg.org/spec/Commons/Collections/
    version: external
  - moduleIri: https://www.omg.org/spec/Commons/ContextualDesignators/
    version: external
  - moduleIri: https://www.omg.org/spec/Commons/DatesAndTimes/
    version: external
  - moduleIri: https://www.omg.org/spec/Commons/Documents/
    version: external
  - moduleIri: https://www.omg.org/spec/Commons/PartiesAndSituations/
    version: external
  exports: []
  status: reference
  governance:
    ownerRef: urn:axiolune:authority:fibo-edmcouncil
    status: reference
  sourceArtifact: LoanApplications.rdf
  sourceDigest: sha256:ad7df5c986fa0bf6d1e108aff41f9772e18303b6300d97e3e0d5e7f6de038f67
  sourcePath: LOAN/LoansGeneral/LoanApplications.rdf
  fiboDomain: LOAN
domain:
  objectTypes:
    AllBorrowersMonthlyIncome:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/AllBorrowersMonthlyIncome
      namespace: fibo-loan-loaloa
      localName: AllBorrowersMonthlyIncome
      label: all borrowers' monthly income
      definition: total monthly qualifying income for all borrowers on the loan
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/CurrencyAmount/MonetaryAmount
      - https://spec.edmcouncil.org/fibo/ontology/FND/OwnershipAndControl/Ownership/Income
      attributeUses: []
      patternBindings: []
    BorrowerAssessment:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/BorrowerAssessment
      namespace: fibo-loan-loaloa
      localName: BorrowerAssessment
      label: borrower assessment
      definition: assessment report detailing information about the borrower and their credit history that may be relevant
        to the loan application
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Assessments/AssessmentReport
      attributeUses: []
      patternBindings: []
    BorrowerMonthlyIncome:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/BorrowerMonthlyIncome
      namespace: fibo-loan-loaloa
      localName: BorrowerMonthlyIncome
      label: borrower monthly income
      definition: total monthly qualifying income of a potential borrower
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/CurrencyAmount/MonetaryAmount
      - https://spec.edmcouncil.org/fibo/ontology/FND/OwnershipAndControl/Ownership/Income
      attributeUses: []
      patternBindings: []
    CreditRiskAssessment:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/CreditRiskAssessment
      namespace: fibo-loan-loaloa
      localName: CreditRiskAssessment
      label: credit risk assessment
      definition: risk assessment that focuses on determining the likelihood of a potential borrower repaying a loan
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Assessments/AssessmentActivity
      attributeUses: []
      patternBindings: []
    IncomeVerificationReport:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/IncomeVerificationReport
      namespace: fibo-loan-loaloa
      localName: IncomeVerificationReport
      label: income verification report
      definition: report providing the methodology and supporting documentation used to verify the borrower's income
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Assessments/AssessmentReport
      attributeUses: []
      patternBindings: []
    IndividualPersonCreditRating:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/IndividualPersonCreditRating
      namespace: fibo-loan-loaloa
      localName: IndividualPersonCreditRating
      label: individual person credit rating
      definition: credit rating that provides an opinion of the creditworthiness of a person
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/FBC/DebtAndEquities/CreditRatings/CreditRating
      attributeUses: []
      patternBindings: []
    LoanApplication:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplication
      namespace: fibo-loan-loaloa
      localName: LoanApplication
      label: loan application
      definition: request by a potential borrower to a potential lender to borrow money containing information used to decide
        whether to grant the loan
      superTypes:
      - https://www.omg.org/spec/Commons/Documents/Document
      attributeUses: []
      patternBindings: []
    LoanApplicationAtAgreementStage:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationAtAgreementStage
      namespace: fibo-loan-loaloa
      localName: LoanApplicationAtAgreementStage
      label: loan application at agreement stage
      definition: ''
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationStatus
      attributeUses: []
      patternBindings: []
    LoanApplicationAtDisbursementStage:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationAtDisbursementStage
      namespace: fibo-loan-loaloa
      localName: LoanApplicationAtDisbursementStage
      label: loan application at disbursement stage
      definition: ''
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationStatus
      attributeUses: []
      patternBindings: []
    LoanApplicationPhase:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationPhase
      namespace: fibo-loan-loaloa
      localName: LoanApplicationPhase
      label: loan application phase
      definition: ''
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Lifecycles/LifecycleStage
      attributeUses: []
      patternBindings: []
    LoanApplicationStatus:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationStatus
      namespace: fibo-loan-loaloa
      localName: LoanApplicationStatus
      label: loan application status
      definition: ''
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Lifecycles/LifecycleStatus
      attributeUses: []
      patternBindings: []
    LoanAtApplicationStage:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanAtApplicationStage
      namespace: fibo-loan-loaloa
      localName: LoanAtApplicationStage
      label: loan at application stage
      definition: ''
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationStatus
      attributeUses: []
      patternBindings: []
    PreApprovalContract:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/PreApprovalContract
      namespace: fibo-loan-loaloa
      localName: PreApprovalContract
      label: pre-approval contract
      definition: written commitment to lend when specified conditions are met, such as finding suitable property, and unchanged
        creditworthiness
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/FND/Agreements/Contracts/WrittenContract
      attributeUses: []
      patternBindings: []
    PreApprovalRequest:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/PreApprovalRequest
      namespace: fibo-loan-loaloa
      localName: PreApprovalRequest
      label: pre-approval request
      definition: request from a potential borrower that a lender commit to pre-approving the borrower for a loan of up to
        a specified amount of money
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Reporting/RequestActivity
      attributeUses: []
      patternBindings: []
    PublicRecord:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/PublicRecord
      namespace: fibo-loan-loaloa
      localName: PublicRecord
      label: public record
      definition: record about an action involving a party that is publicly available from a court or other government agency
      superTypes:
      - https://www.omg.org/spec/Commons/Documents/Record
      attributeUses: []
      patternBindings: []
    PublicRecordCategory:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/PublicRecordCategory
      namespace: fibo-loan-loaloa
      localName: PublicRecordCategory
      label: public record category
      definition: classifier of public records relevant to a loan application, e.g. tax lien, wage garnishment, foreclosure
      superTypes:
      - https://www.omg.org/spec/Commons/Classifiers/Classifier
      attributeUses: []
      patternBindings: []
    TotalDebtExpenseRatio:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/TotalDebtExpenseRatio
      namespace: fibo-loan-loaloa
      localName: TotalDebtExpenseRatio
      label: total debt expense ratio
      definition: ratio of all monthly debt payments of all borrowers, including proposed expenses, with respect to the income
        of the borrowers as relied upon to make a credit decision
      superTypes:
      - https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/CurrencyAmount/PercentageMonetaryAmount
      attributeUses: []
      patternBindings: []
    UnderwritingAutomation:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/UnderwritingAutomation
      namespace: fibo-loan-loaloa
      localName: UnderwritingAutomation
      label: underwriting automation
      definition: classifier indicating whether a loan was underwritten manually or using an automated underwriting system
      superTypes:
      - https://www.omg.org/spec/Commons/Classifiers/Classifier
      attributeUses: []
      patternBindings: []
    UnderwritingDecision:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/UnderwritingDecision
      namespace: fibo-loan-loaloa
      localName: UnderwritingDecision
      label: underwriting decision
      definition: classifier providing a loan approval recommendation determined either manually or by an automated underwriting
        system
      superTypes:
      - https://www.omg.org/spec/Commons/Classifiers/Classifier
      attributeUses: []
      patternBindings: []
  associationTypes: {}
  relationTypes:
    hasApplicationDate:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/hasApplicationDate
      namespace: fibo-loan-loaloa
      localName: hasApplicationDate
      label: has application date
      definition: date on which an application was signed and submitted
      domain: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplication
      range: https://www.omg.org/spec/Commons/DatesAndTimes/ExplicitDate
      inverseOf: ''
      characteristics: []
    hasApplicationPhase:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/hasApplicationPhase
      namespace: fibo-loan-loaloa
      localName: hasApplicationPhase
      label: has application phase
      definition: The phase within the application lifecycle, that this Loan Application is at,
      domain: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplication
      range: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationPhase
      inverseOf: ''
      characteristics: []
    hasApprovedAmount:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/hasApprovedAmount
      namespace: fibo-loan-loaloa
      localName: hasApprovedAmount
      label: has approved amount
      definition: relates something, e.g. a loan, to the amount of funds approved
      domain: ''
      range: ''
      inverseOf: ''
      characteristics: []
    hasGrossIncome:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/hasGrossIncome
      namespace: fibo-loan-loaloa
      localName: hasGrossIncome
      label: has gross income
      definition: indicates the personal gross income of the borrower
      domain: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/BorrowerAssessment
      range: https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/CurrencyAmount/MonetaryAmount
      inverseOf: ''
      characteristics: []
    hasRequestedAmount:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/hasRequestedAmount
      namespace: fibo-loan-loaloa
      localName: hasRequestedAmount
      label: has requested amount
      definition: relates something, e.g. a request for a loan, to the amount of funds requested
      domain: ''
      range: ''
      inverseOf: ''
      characteristics: []
    usesFactor:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/usesFactor
      namespace: fibo-loan-loaloa
      localName: usesFactor
      label: uses factor
      definition: relates e.g. a risk assessment to something used as a factor to make the assessment
      domain: ''
      range: ''
      inverseOf: ''
      characteristics: []
  attributeTypes:
    hasIntendedLoanPurpose:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/hasIntendedLoanPurpose
      namespace: fibo-loan-loaloa
      localName: hasIntendedLoanPurpose
      label: has intended loan purpose
      definition: indicates the purpose to which the loaned funds are to be put
      valueType: string
      defaultCardinality:
        minCount: 0
        maxCount: null
    hasOriginalLoanDebtToIncomeRatio:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/hasOriginalLoanDebtToIncomeRatio
      namespace: fibo-loan-loaloa
      localName: hasOriginalLoanDebtToIncomeRatio
      label: has original loan debt-to-income ratio
      definition: indicates the debt-to-income (DTI) ratio at the time when the loan was advanced; for combined income
      valueType: decimal
      defaultCardinality:
        minCount: 0
        maxCount: null
    isPreApprovalRequested:
      iri: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/isPreApprovalRequested
      namespace: fibo-loan-loaloa
      localName: isPreApprovalRequested
      label: is pre-approval requested
      definition: indicates whether a pre-approval has been requested, in conjunction with a loan application
      valueType: boolean
      defaultCardinality:
        minCount: 0
        maxCount: null
  identifierTypes: {}
  codeLists: {}
  constraints: {}
